[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true
  headers = { 
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate",
    Pragma = "no-cache",
    Expires = "0"
  }
